import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'am', label: 'Amharic', native: 'አማርኛ' },
  { code: 'om', label: 'Oromo', native: 'Afaan Oromoo' },
  { code: 'wot', label: 'Wolaytta', native: 'ወላይታቱ' },
  { code: 'ti', label: 'Tigrinya', native: 'ትግርኛ' },
];

export const translations = {
  en: {
    brandName: 'AgroConnect Ethiopia',
    tagline: 'Connecting Farmers, Cooperatives & Buyers Nationwide',
    browseProducts: 'Browse Marketplace',
    marketPrices: 'Price Radar & Arbitrage',
    logistics: 'Freight & Truck Sharing',
    cropAdvisory: 'Crop Health & Pest AI',
    myDashboard: 'Farmer Dashboard',
    myOrders: 'My Requests & Escrow',
    messages: 'Messages',
    adminDashboard: 'Admin Dashboard',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    getStarted: 'Get Started Free',
    heroTitle: 'Empowering Ethiopian Agriculture from Farmgate to National Markets',
    heroSubtitle: 'Direct crop trade, cooperative aggregation, Telebirr escrow protection, and return-trip freight sharing — ending broker exploitation and cutting post-harvest losses.',
    threeStepsTitle: 'How AgroConnect Works Across Ethiopia',
    step1Title: '1. Farmers & Unions List Produce',
    step1Text: 'Post single farm harvests or cooperative pooled lots with verified grades (Grade 1/2, Organic).',
    step2Title: '2. Direct Trade & Price Radar',
    step2Text: 'Compare farmgate prices with Addis Ababa terminal markets to lock in fair, transparent deals.',
    step3Title: '3. Telebirr Escrow & Logistics',
    step3Text: 'Buyers pay into secured escrow; drivers fill empty truck capacity; funds release on verified arrival.',
    featuredHarvests: 'Featured Produce from Ethiopian Regions',
    viewAllProducts: 'View All Harvests',
    priceRadarHeadline: 'National Market Price & Arbitrage Radar',
    arbitrageSubtitle: 'Real-time price spreads between regional farmgates and central terminal markets (Ehil Berenda / Adama / Merkato).',
    freightBannerTitle: 'Rural Isuzu & FSR Truck Sharing',
    freightBannerSubtitle: 'Save up to 40% by booking return-trip empty truck capacity between regional hubs and major cities.',
    diseaseAdvisoryTitle: 'Crop Disease & Pest Diagnostics',
    diseaseAdvisorySubtitle: 'Identify and treat Enset bacterial wilt, Coffee berry disease, Maize armyworm, and Wheat rust.',
    searchPlaceholder: 'Search by crop, region, or keyword...',
    filterRegion: 'Filter Region',
    filterCategory: 'Category',
    filterGrade: 'Quality Grade',
    allRegions: 'All Regions (Nationwide)',
    price: 'Price',
    quantity: 'Quantity',
    unit: 'Unit',
    location: 'Location',
    grade: 'Grade',
    harvestDate: 'Harvest Date',
    coopPooled: 'Cooperative Pooled Lot',
    buyDirectEscrow: 'Buy with Telebirr / CBE Escrow',
    escrowGuarantee: '🔒 100% Escrow Protection: Funds held securely until you inspect & confirm delivery.',
    messageSeller: 'Message Seller',
    seller: 'Seller',
    requestProduce: 'Request this Harvest',
    paymentMethod: 'Payment Method',
    telebirr: 'Telebirr (Ethio Telecom)',
    cbeBirr: 'CBE Birr (Commercial Bank of Ethiopia)',
    cashOnDelivery: 'Cash on Delivery / Inspection',
    statusPending: 'Pending Confirmation',
    statusEscrow: 'Telebirr Escrow Held',
    statusTransit: 'Dispatched / In Freight',
    statusCompleted: 'Delivered & Funds Released',
    confirmReceipt: 'Confirm Receipt & Release Escrow',
    bookFreight: 'Book Cargo Space',
    availableCapacity: 'Available Capacity',
    pricePerQuintal: 'Price per Quintal',
    origin: 'Origin',
    destination: 'Destination',
    departure: 'Departure',
    symptoms: 'Symptoms',
    prevention: 'Prevention',
    organicCure: 'Organic Treatment',
    chemicalAdvice: 'Ministry of Agriculture Guidelines',
  },
  am: {
    brandName: 'አግሮኮኔክት ኢትዮጵያ',
    tagline: 'አርሶ አደሮችን፣ ዩኒየኖችን እና ነጋዴዎችን በመላው ሀገሪቱ የሚያስተሳስር',
    browseProducts: 'ምርቶችን ይመልከቱ',
    marketPrices: 'የዋጋ ንጽጽርና መረጃ',
    logistics: 'የጭነት መኪና ማዛመጃ',
    cropAdvisory: 'የሰብል ጤና እና ተባይ መመሪያ',
    myDashboard: 'የአርሶ አደር ዳሽቦርድ',
    myOrders: 'ትዕዛዞችና ክፍያ',
    messages: 'መልዕክቶች',
    adminDashboard: 'የአስተዳዳሪ ክፍል',
    login: 'ይግቡ',
    register: 'ይመዝገቡ',
    logout: 'ውጣ',
    getStarted: 'አሁኑኑ ይጀምሩ',
    heroTitle: 'የኢትዮጵያን ግብርና ከአምራች እስከ ማዕከላዊ ገበያ የሚያገናኝ ዲጂታል መድረክ',
    heroSubtitle: 'ያለ ደላላ ቀጥታ ግብይት፣ የህብረት ስራ ማህበራት ምርት ስብስብ፣ በቴሌብር የዋስትና ክፍያ እና የመመለሻ የጭነት መኪና ቅንጅት።',
    threeStepsTitle: 'አግሮኮኔክት እንዴት ይሰራል?',
    step1Title: '1. ምርት መመዝገብ',
    step1Text: 'አርሶ አደሮችና ማህበራት ምርቶቻቸውን በጥራት ደረጃ (ደረጃ 1/2) እና በኩንታል ይመዘግባሉ።',
    step2Title: '2. የገበያ ዋጋ ንጽጽር',
    step2Text: 'የክልል መነሻ ዋጋን ከአዲስ አበባ እህል በረንዳና አዳማ ገበያ ጋር በማወዳደር ትክክለኛ ዋጋ ያግኙ።',
    step3Title: '3. የቴሌብር ዋስትናና ጭነት',
    step3Text: 'ገዢዎች ክፍያውን በዋስትና (Escrow) ይይዛሉ፤ ምርቱ ሲደርስና ሲረጋገጥ ክፍያው ለአርሶ አደሩ ይለቀቃል።',
    featuredHarvests: 'የተመረጡ የሀገር ውስጥ ሰብሎች',
    viewAllProducts: 'ሁሉንም ምርቶች ይመልከቱ',
    priceRadarHeadline: 'የሀገር አቀፍ የገበያ ዋጋና የትርፍ ንጽጽር (Arbitrage)',
    arbitrageSubtitle: 'በአምራች ገበያዎች እና ማዕከላዊ እህል በረንዳ መሀከል ያለውን የዋጋ ልዩነት በቀጥታ ይመልከቱ።',
    freightBannerTitle: 'የኢሱዙና ኤፍ.ኤስ.አር (FSR) የመመለሻ ጭነት ማዛመጃ',
    freightBannerSubtitle: 'ባዶ የሚመለሱ መኪኖችን በመጠቀም የትራንስፖርት ወጪዎን እስከ 40% ይቀንሱ።',
    diseaseAdvisoryTitle: 'የሰብል በሽታዎችና ተባይ መከላከያ መመሪያ',
    diseaseAdvisorySubtitle: 'የእንሰት ባክቴሪያል ዊልት (ጎመሬ)፣ የቡና ሲ.ቢ.ዲ፣ የበቆሎ አባጨጓሬ እና የጤፍ ዝገት መከላከያ መፍትሄዎች።',
    searchPlaceholder: 'በሰብል፣ በክልል ወይም በከተማ ይፈልጉ...',
    filterRegion: 'ክልል ይምረጡ',
    filterCategory: 'ምድብ',
    filterGrade: 'የጥራት ደረጃ',
    allRegions: 'ሁሉም የኢትዮጵያ ክልሎች',
    price: 'ዋጋ',
    quantity: 'መጠን',
    unit: 'መለኪያ',
    location: 'አካባቢ',
    grade: 'ደረጃ',
    harvestDate: 'የተሰበሰበበት ቀን',
    coopPooled: 'የህብረት ስራ ማህበር የጋራ ምርት',
    buyDirectEscrow: 'በቴሌብር ዋስትና ይዘዙ',
    escrowGuarantee: '🔒 100% የቴሌብር ዋስትና፡ ምርቱን ተረክበው እስኪያረጋግጡ ድረስ ገንዘብዎ በአስተማማኝ ሁኔታ ተጠብቆ ይቆያል።',
    messageSeller: 'ከሻጩ ጋር ይወያዩ',
    seller: 'አምራች/ሻጭ',
    requestProduce: 'ምርቱን ይዘዙ',
    paymentMethod: 'የክፍያ አማራጭ',
    telebirr: 'ቴሌብር (ኢትዮ ቴሌኮም)',
    cbeBirr: 'ሲቢኢ ብር (የኢትዮጵያ ንግድ ባንክ)',
    cashOnDelivery: 'በእጅ ሲረከቡ',
    statusPending: 'በመጠባበቅ ላይ',
    statusEscrow: 'ገንዘቡ በቴሌብር ዋስትና ተይዟል',
    statusTransit: 'በመጓጓዝ ላይ (በጭነት)',
    statusCompleted: 'ተረክበዋል & ክፍያው ተለቋል',
    confirmReceipt: 'ምርቱን ተረክቤያለሁ - ክፍያው ይለቀቅ',
    bookFreight: 'የጭነት ቦታ ይያዙ',
    availableCapacity: 'ያለ ክፍት ቦታ',
    pricePerQuintal: 'ዋጋ በኩንታል',
    origin: 'መነሻ',
    destination: 'መድረሻ',
    departure: 'የሚነሳበት ቀን',
    symptoms: 'ምልክቶች',
    prevention: 'መከላከያ',
    organicCure: 'ተፈጥሯዊ ማከሚያ',
    chemicalAdvice: 'የግብርና ሚኒስቴር መመሪያ',
  },
  om: {
    brandName: 'AgroConnect Itoophiyaa',
    tagline: 'Qonnaan bultoota, Yuuniyeenotaa fi Daldaltoota Biyyaalessaa Walqunnamsiisu',
    browseProducts: 'Oomishaalee Daawwadhaa',
    marketPrices: 'Gatii Gabaa fi Qorannoo',
    logistics: 'Konkolaataa Fe’iinsaa',
    cropAdvisory: 'Fayyaa Midhaanii fi Raammoo',
    myDashboard: 'Gabaasa Qonnaan Bulaa',
    myOrders: 'Ajaja koo fi Kaffaltii',
    messages: 'Ergaawwan',
    adminDashboard: 'Gabaasa Bulchaa',
    login: 'Seenaa',
    register: 'Galmaa’aa',
    logout: 'Bahaa',
    getStarted: 'Tola Jalqabaa',
    heroTitle: 'Qonna Itoophiyaa Qonnaan Bulaarraa Hanga Gabaa Giddugaleessaatti Ceesisuu',
    heroSubtitle: 'Daldala qajeeltoo giddu-galeessa malee, waldaalee qonnaan bultootaa, wabii kaffaltii Telebirr fi fe’iinsa konkolaataa.',
    threeStepsTitle: 'AgroConnect Akkamitti Hojjeta?',
    step1Title: '1. Oomisha Galmeessuu',
    step1Text: 'Qonnaan bultoonni fi yuuniyeenonni oomisha isaanii sadarkaa qulqullinaa wajjin galmeessu.',
    step2Title: '2. Gatii Gabaa Walbira Qabuu',
    step2Text: 'Gatii bakka oomishaa fi Finfinnee (Ihil Berenda) walbira qabuun daldalaa.',
    step3Title: '3. Wabii Telebirr fi Fe’iinsa',
    step3Text: 'Gatiin Telebirr keessatti qabama; oomishni yoo qaqqabe kaffaltiin qonnaan bulaaf darba.',
    featuredHarvests: 'Oomishaalee Filataman',
    viewAllProducts: 'Oomisha Hunda Ilaalaa',
    priceRadarHeadline: 'Gatii Gabaa Biyyaalessaa',
    arbitrageSubtitle: 'Garaagarummaa gatii gabaa naannolee fi Finfinnee gidduu jiru hordofaa.',
    freightBannerTitle: 'Fe’iinsa Konkolaataa Isuzu fi FSR',
    freightBannerSubtitle: 'Konkolaattota duwwaa deebi’an fayyadamuun baasii geejjibaa hanga 40% hir’isaa.',
    diseaseAdvisoryTitle: 'Qoricha fi Dhukkuboota Midhaanii',
    diseaseAdvisorySubtitle: 'Bacterial wilt qoccoo, dhukkuba firi bunaa (CBD), raammoo boqqolloo fi wagii xaafii to’adhaa.',
    searchPlaceholder: 'Midhaan, naannoo ykn magaalaan barbaadaa...',
    filterRegion: 'Naannoo Filadhaa',
    filterCategory: 'Gosa',
    filterGrade: 'Sadarkaa Qulqullinaa',
    allRegions: 'Naannolee Hunda',
    price: 'Gatii',
    quantity: 'Hamma',
    unit: 'Safartuu',
    location: 'Bakka',
    grade: 'Sadarkaa',
    harvestDate: 'Guyyaa Haamame',
    coopPooled: 'Oomisha Gamtaa Waldaa',
    buyDirectEscrow: 'Wabii Telebirriin Bitaa',
    escrowGuarantee: '🔒 Wabii Telebirr 100%: Hanga oomisha fuutanii mirkaneessitanitti qarshiin keessan eegama.',
    messageSeller: 'Gurguraa Dubbisaa',
    seller: 'Gurguraa',
    requestProduce: 'Oomisha Ajajaa',
    paymentMethod: 'Mala Kaffaltii',
    telebirr: 'Telebirr (Ethio Telecom)',
    cbeBirr: 'CBE Birr (Baankii Daldala Itoophiyaa)',
    cashOnDelivery: 'Yeroo Qaqqabu',
    statusPending: 'Eeggachaa jira',
    statusEscrow: 'Qarshiin Telebirr keessa jira',
    statusTransit: 'Karaa irratti',
    statusCompleted: 'Qaqqabeera & Kaffalameera',
    confirmReceipt: 'Oomisha Fuadheera - Qarshiin haa darbu',
    bookFreight: 'Bakka Fe’iinsaa Qabadhaa',
    availableCapacity: 'Bakka Duwwaa',
    pricePerQuintal: 'Gatii Kuntaala tokkoo',
    origin: 'Ka’umsa',
    destination: 'Gahumsa',
    departure: 'Guyyaa Ka’umsaa',
    symptoms: 'Mallattoolee',
    prevention: 'Ittisa',
    organicCure: 'Yaala Uumamaa',
    chemicalAdvice: 'Qajeelfama Ministeera Qonnaa',
  },
  wot: {
    brandName: 'AgroConnect Itoophiyaa',
    tagline: 'Goshshanchata, Heebretaa Maabaratanne Aycciyagata Issife Gathiyaa',
    browseProducts: 'Kathaa Beeyite',
    marketPrices: 'Gabaa Wagaa Qonccissiyo',
    logistics: 'Toshshiyo Makiniya',
    cropAdvisory: 'Kathiye Harge Teqqiyo Erissiyo',
    myDashboard: 'Goshshancha Dashbordiya',
    myOrders: 'Tawu Kiittido Ooshshata',
    messages: 'Kiitaa',
    adminDashboard: 'Astemariya Kessa',
    login: 'Gellite',
    register: 'Xaafeettite',
    logout: 'Kiyyite',
    getStarted: 'Haani Doomite',
    heroTitle: 'Itoophiya Goshshatethaa Gadiyaappe Gabaa Giddo Gathiyo Dijiitaliya',
    heroSubtitle: 'Dalalayi bayina qoncce zalqqiya, Heebreta Maabareti kathiya issife shishiyo, Telebirre waasina kiffilatanne togisiya makiniyara.',
    threeStepsTitle: 'AgroConnect Waani Ooshettii?',
    step1Title: '1. Kathaa Qonccissiyo',
    step1Text: 'Goshshanchati loe katha bantta qofa woyikko maabarappe shishidi qonccissoosona.',
    step2Title: '2. Gabaa Wagaa Qanxiyo',
    step2Text: 'Bantta biitta gabaa Finfinne Ehil Berendara geeddarssidi tuma wagaa demmite.',
    step3Title: '3. Telebirrenne Toshshiyo',
    step3Text: 'Shamiyaagee Telebirren wotidi kathay gakkishin erissidi qofa goshshanchawu aathosi.',
    featuredHarvests: 'Doorettida Kathata',
    viewAllProducts: 'Ubba Kathaa Beeyite',
    priceRadarHeadline: 'Biitta Gabaa Wagaa Geeddarssiyo',
    arbitrageSubtitle: 'Biittan kathiye bayiyo wagaaranne katama gabaa giddo deyiya wagaa beeyite.',
    freightBannerTitle: 'Isuzu FSR Makiniya Toshsho Shisshiyo',
    freightBannerSubtitle: 'Mela simmiya makiniyatan toshshidi 40% woshshu gakkanawu wagaa guuxxite.',
    diseaseAdvisoryTitle: 'Kathiya Hargenne Kishshiya Teqqiyo',
    diseaseAdvisorySubtitle: 'Wosa dangisa (Gomere), Buuniya CBD, Badala yilliyeta teqqiyo ogiya erite.',
    searchPlaceholder: 'Kathan, biittan woyikko kataman koyite...',
    filterRegion: 'Biittaa Doorite',
    filterCategory: 'Qommuwa',
    filterGrade: 'Qulqullatetha',
    allRegions: 'Ubba Itoophiya Biittata',
    price: 'Wagaa',
    quantity: 'Tayppiya',
    unit: 'Pisiya',
    location: 'Saata',
    grade: 'Loe Detha',
    harvestDate: 'Qanxxido Gala',
    coopPooled: 'Maabari Issife Shishshido Kathaa',
    buyDirectEscrow: 'Telebirre Waasinaan Shamite',
    escrowGuarantee: '🔒 100% Telebirre Waasina: Kathay intte kusha gakkanaashin miishshay loeyada naagetteesi.',
    messageSeller: 'Aysiyaagawu Kiitite',
    seller: 'Aysiyaaga',
    requestProduce: 'Kathaa Shamite',
    paymentMethod: 'Kiffilati Ogiya',
    telebirr: 'Telebirr (Ethio Telecom)',
    cbeBirr: 'CBE Birr (Baanke)',
    cashOnDelivery: 'Gakkishin Kushiyan',
    statusPending: 'Naagetteysi',
    statusEscrow: 'Miishshay Telebirren Naagetteesi',
    statusTransit: 'Makiniyan Yiiddi Deesi',
    statusCompleted: 'Gakkis & Miishshay Aathis',
    confirmReceipt: 'Kathaa Ekkas - Miishshay Kifetto',
    bookFreight: 'Toshsho Sohuwa Oyqqite',
    availableCapacity: 'Deeyiya Sohuwa',
    pricePerQuintal: 'Kuntaala Wagaa',
    origin: 'Kessiyo Saa',
    destination: 'Gathiyo Saa',
    departure: 'Kessiyo Gala',
    symptoms: 'Malatata',
    prevention: 'Teqqiyo Ogiya',
    organicCure: 'Dura Xaliya',
    chemicalAdvice: 'Goshsha Ministiriya Erishe',
  },
  ti: {
    brandName: 'አግሮኮኔክት ኢትዮጵያ',
    tagline: 'ሓረስቶት፣ ሕብረት ማሕበራትን ነጋዶን ዘራኽብ መድረኽ',
    browseProducts: 'ፍርያት ርኣዩ',
    marketPrices: 'ዋጋ ዕዳጋን ንጽጽርን',
    logistics: 'መጓዓዝያ ጽዕነት',
    cropAdvisory: 'ጥዕና ዘርኢን ምቁጽጻር ባልዕን',
    myDashboard: 'ዳሽቦርድ ሓረስታይ',
    myOrders: 'ትእዛዛተይን ክፍሊትን',
    messages: 'መልእኽቲታት',
    adminDashboard: 'ክፍሊ ኣመሓዳሪ',
    login: 'እተዉ',
    register: 'ተመዝገቡ',
    logout: 'ውፃእ',
    getStarted: 'ሕጂ ጀምሩ',
    heroTitle: 'ሕርሻ ኢትዮጵያ ካብ ሓረስታይ ናብ ማእከላይ ዕዳጋ ዘራኽብ ቴክኖሎጂ',
    heroSubtitle: 'ብዘይ ደላሊ ቀጥታዊ ንግዲ፣ ናይ ማሕበራት ሓባራዊ ምድላው፣ ናይ ቴሌብር ውሕስነት ክፍሊትን ምምላስ መኪና ምትሕብባርን።',
    threeStepsTitle: 'አግሮኮኔክት ከመይ ይሰርሕ?',
    step1Title: '1. ፍርያት ምምዝጋብ',
    step1Text: 'ሓረስቶትን ሕብረት ማሕበራትን ፍርያቶም ብደረጃ ጽሬት ይምዝግቡ።',
    step2Title: '2. ንጽጽር ዋጋ ዕዳጋ',
    step2Text: 'ናይ ከባቢ ዋጋ ምስ ማእከላይ ዕዳጋታት ብምንጽጻር ቅኑዕ ዋጋ ረኽቡ።',
    step3Title: '3. ውሕስነት ቴሌብርን ጽዕነትን',
    step3Text: 'ገዛኢ ብቴሌብር ይኸፍል፤ ፍርያት ብትኽክል ምስ በጽሐ ክፍሊት ናብ ሓረስታይ ይለኣኽ።',
    featuredHarvests: 'ዝተመርጹ ፍርያታት',
    viewAllProducts: 'ኩሉ ፍርያት ርኣዩ',
    priceRadarHeadline: 'ዋጋ ዕዳጋ ሃገርን ንጽጽርን',
    arbitrageSubtitle: 'ኣብ መንጎ ከባብያዊ ዕዳጋታትን ማእከላይ ዕዳጋታትን ዘሎ ፍልልይ ዋጋ ተዓዘቡ።',
    freightBannerTitle: 'መጓዓዝያ ኢሱዙን ኤፍ.ኤስ.ኣርን (FSR)',
    freightBannerSubtitle: 'ጥራሖም ዝምለሱ መኻይን ብምጥቃም ናይ መጓዓዝያ ወጻኢታትኩም ክሳብ 40% ኣጉድሉ።',
    diseaseAdvisoryTitle: 'ምቁጽጻር ሕማማትን ባልዕን',
    diseaseAdvisorySubtitle: 'ሕማም እንሰት፣ ናይ ቡን ሲ.ቢ.ዲ፣ ናይ ዕፉን ባልዕን ናይ ጣፍ ዋግን ምክልኻል።',
    searchPlaceholder: 'ብፍርያት፣ ብክልል ወይ ብከተማ ድለዩ...',
    filterRegion: 'ክልል ምረጹ',
    filterCategory: 'ዓይነት',
    filterGrade: 'ደረጃ ጽሬት',
    allRegions: 'ኩሎም ክልላት ኢትዮጵያ',
    price: 'ዋጋ',
    quantity: 'መጠን',
    unit: 'መለክዒ',
    location: 'ቦታ',
    grade: 'ደረጃ',
    harvestDate: 'ዝተዓጽደሉ ዕለት',
    coopPooled: 'ናይ ሕብረት ማሕበር ሓባራዊ ፍርያት',
    buyDirectEscrow: 'ብውሕስነት ቴሌብር ግዝኡ',
    escrowGuarantee: '🔒 100% ውሕስነት ቴሌብር፡ ፍርያት ተረኪብኩም ክሳብ ተረጋግጹ ገንዘብኩም ብውሑስ መንገዲ ይተሓዝ።',
    messageSeller: 'ምስ ሸያጢ ተዘራረቡ',
    seller: 'ሸያጢ/ሓረስታይ',
    requestProduce: 'ፍርያት እዘዙ',
    paymentMethod: 'መንገዲ ክፍሊት',
    telebirr: 'ቴሌብር (ኢትዮ ቴሌኮም)',
    cbeBirr: 'ሲቢኢ ብር (ንግዲ ባንኪ)',
    cashOnDelivery: 'ምስ ተረከብኩም',
    statusPending: 'ይጽበ ኣሎ',
    statusEscrow: 'ገንዘብ ብቴሌብር ተታሒዙ ኣሎ',
    statusTransit: 'ኣብ መገዲ ኣሎ',
    statusCompleted: 'ተበጺሑ & ክፍሊት ተለቒቑ',
    confirmReceipt: 'ፍርያት ተረኪበ ኣለኹ - ክፍሊት ይለቀቕ',
    bookFreight: 'ቦታ ጽዕነት ሓዙ',
    availableCapacity: 'ክፉት ቦታ',
    pricePerQuintal: 'ዋጋ ብኩንታል',
    origin: 'መበገሲ',
    destination: 'መዕረፊ',
    departure: 'ዝብገሰሉ ዕለት',
    symptoms: 'ምልክታት',
    prevention: 'ምክልኻል',
    organicCure: 'ተፈጥሮኣዊ ፍወሳ',
    chemicalAdvice: 'መምርሒ ሚኒስትሪ ሕርሻ',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('agroconnect_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('agroconnect_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
